<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * CarPhoto model — stores image URLs and optional AI-generated tags.
 *
 * @property int         $id
 * @property int         $car_id
 * @property string      $url         Publicly accessible image URL.
 * @property int         $sort_order  Display order (0 = primary photo).
 * @property array|null  $ai_tags     JSON array of tags generated by the vision model.
 */
class CarPhoto extends Model
{
    use HasFactory;

    /** @var list<string> */
    protected $fillable = ['car_id', 'url', 'sort_order', 'ai_tags'];

    /** @var array<string, string> */
    protected $casts = [
        'sort_order' => 'integer',
        'ai_tags'    => 'array',
    ];

    /**
     * The car this photo belongs to.
     *
     * @return BelongsTo<Car, CarPhoto>
     */
    public function car(): BelongsTo
    {
        return $this->belongsTo(Car::class);
    }
}
